name: install-matrix
permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install deps
        run: npm install --frozen-lockfile
      - name: Build package
        run: npm run build
      - name: Pack tarball
        run: npm pack

      - name: Node ESM import smoke
        run: node scripts/smoke/node-esm.mjs kittycad-lib-*.tgz

      - name: Node CJS require smoke
        run: node scripts/smoke/node-cjs.cjs kittycad-lib-*.tgz

      - name: Browser bundling (esbuild) smoke
        run: node scripts/smoke/esbuild.mjs kittycad-lib-*.tgz

      - name: Browser bundling (Vite) smoke
        run: node scripts/smoke/vite.mjs kittycad-lib-*.tgz
