on:
  push:
    branches:
      - main
name: make-release
jobs:
  makerelease:
    permissions:
      contents: write
    name: make-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: '20.9.0'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'yarn'
      # Only push a tag that matches the version in package.json
      - name: Tag em and bag em
        run: |
          git tag v$(cat package.json | jq -r .version)
          git push origin v$(cat package.json | jq -r .version)
      - name: Build package artifacts
        run: yarn install && yarn build
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
