name: win-ca-smoke

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build SDK
        run: yarn build
      - name: Create and trust local root CA and server cert
        shell: pwsh
        run: |
          ./scripts/win/create-local-ca.ps1 -PfxPath servercert.pfx -PfxPassword 'pass'
      - name: Start HTTPS test server
        shell: pwsh
        run: |
          Start-Job -Name https -ScriptBlock { node scripts/https-server.mjs } | Out-Null
          Start-Sleep -Seconds 2
      - name: Smoke test (TLS with win-ca)
        run: node scripts/win-ca-smoke.mjs
      - name: Stop HTTPS server
        if: always()
        shell: pwsh
        run: |
          Get-Job -Name https | Stop-Job -PassThru | Remove-Job
      - name: Cleanup local certs
        if: always()
        shell: pwsh
        run: |
          try {
            Get-ChildItem -Path Cert:\CurrentUser\Root | Where-Object { $_.Subject -eq 'CN=KittyCAD-Test-Root' } | Remove-Item -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object { $_.Subject -match 'CN=KittyCAD-Test-Root|CN=localhost' } | Remove-Item -Force -ErrorAction SilentlyContinue
          } catch {}
