name: win-ca-smoke

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build SDK
        run: yarn build
      - name: Create and trust local root CA and server cert
        shell: pwsh
        run: |
          ./scripts/win/create-local-ca.ps1 -PfxPath servercert.pfx -PfxPassword 'pass'
      - name: HTTPS smoke (start server and test in one step)
        shell: pwsh
        env:
          NODE_EXTRA_CA_CERTS: ${{ github.workspace }}\root.pem
        run: |
          $job = Start-Job -ScriptBlock { node scripts/https-server.mjs }
          try {
            # Wait for port 4443 to be ready (max 30s)
            $deadline = (Get-Date).AddSeconds(30)
            do {
              $ok = Test-NetConnection -ComputerName 127.0.0.1 -Port 4443 -WarningAction SilentlyContinue -InformationLevel Quiet
              if (-not $ok) { Start-Sleep -Milliseconds 200 }
            } while (-not $ok -and (Get-Date) -lt $deadline)
            if (-not $ok) { throw 'HTTPS server did not become ready in time' }
            node scripts/win-ca-smoke.mjs
          } finally {
            Stop-Job -Job $job -PassThru | Remove-Job
          }
      - name: Cleanup local certs
        if: always()
        shell: pwsh
        run: |
          try {
            # CurrentUser cleanup
            Get-ChildItem -Path Cert:\CurrentUser\Root | Where-Object { $_.Subject -eq 'CN=KittyCAD-Test-Root' } | Remove-Item -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object { $_.Subject -match 'CN=KittyCAD-Test-Root|CN=localhost' } | Remove-Item -Force -ErrorAction SilentlyContinue
          } catch {}
          try {
            # LocalMachine cleanup (default trust scope in CI)
            Get-ChildItem -Path Cert:\LocalMachine\Root | Where-Object { $_.Subject -eq 'CN=KittyCAD-Test-Root' } | Remove-Item -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path Cert:\LocalMachine\My | Where-Object { $_.Subject -match 'CN=KittyCAD-Test-Root|CN=localhost' } | Remove-Item -Force -ErrorAction SilentlyContinue
          } catch {}
