name: win-ca-smoke

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [ main, master ]

env:
  SMOKE_URL: 'https://127.0.0.1:4443/'

jobs:
  smoke:
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    uses: kittycad/gh-action-win-ca/.github/workflows/win-ca-smoke.yml@main
    with:
      node-version: ${{ matrix.node }}
      install-command: |
        npm install --frozen-lockfile
        npm run build
      pre-test-command: node scripts/win-ca-smoke.mjs
      post-test-command: node scripts/win-ca-smoke.mjs
