name: win-ca-smoke

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  smoke:
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    uses: kittycad/gh-action-win-ca/.github/workflows/win-ca-smoke.yml@main
    with:
      node-version: ${{ matrix.node }}
      install-command: |
        npm install --frozen-lockfile
        npm run build
        if (-not (Test-Path 'scripts')) { New-Item -ItemType Directory -Path 'scripts' | Out-Null }
        if (-not (Test-Path 'scripts/win')) { New-Item -ItemType Directory -Path 'scripts/win' | Out-Null }
        Invoke-WebRequest 'https://raw.githubusercontent.com/kittycad/gh-action-win-ca/main/scripts/win/create-local-ca.ps1' -OutFile 'scripts/win/create-local-ca.ps1'
      pre-test-command: node scripts/win-ca-smoke.mjs
      post-test-command: node scripts/win-ca-smoke.mjs
